# gmake
# This file is automatically generated for client.mk.
# Do not edit. Edit /c/Users/imelven/src/sandbox/mozconfig instead.

# PATH=/local/bin:/c/mozilla-build/wget:/c/mozilla-build/7zip:/c/mozilla-build/blat261/full:/c/mozilla-build/python:/c/mozilla-build/svn-win32-1.6.3/bin:/c/mozilla-build/upx203w:/c/mozilla-build/emacs-22.3/bin:/c/mozilla-build/info-zip:/c/mozilla-build/nsis-2.22:/c/mozilla-build/nsis-2.33u:/c/mozilla-build/nsis-2.46u:/c/mozilla-build/wix-351728:/c/mozilla-build/hg:/c/mozilla-build/python/Scripts:/c/mozilla-build/kdiff3:/c/mozilla-build/yasm:.:/usr/local/bin:/mingw/bin:/bin:/c/Program Files (x86)/Microsoft Visual Studio 10.0/VSTSDB/Deploy:/c/Program Files (x86)/Microsoft Visual Studio 10.0/Common7/IDE/:/c/Program Files (x86)/Microsoft Visual Studio 10.0/VC/BIN:/c/Program Files (x86)/Microsoft Visual Studio 10.0/Common7/Tools:/c/Windows/Microsoft.NET/Framework/v4.0.30319:/c/Windows/Microsoft.NET/Framework/v3.5:/c/Program Files (x86)/Microsoft Visual Studio 10.0/VC/VCPackages:/c/Program Files (x86)/HTML Help Workshop:/c/Program Files (x86)/Microsoft SDKs/Windows/v7.0A/bin/NETFX 4.0 Tools:/c/Program Files (x86)/Microsoft SDKs/Windows/v7.0A/bin:/c/Windows/System32:/c/Windows:/c/Windows/System32/Wbem:/c/mozilla-build/moztools/bin:/c/mozilla-build/vim/vim72
# --enable-application=browser is used by configure (not client.mk)
MOZ_OBJDIR=$(TOPSRCDIR)/objdir-dbg
# --disable-optimize is used by configure (not client.mk)
# --enable-debug is used by configure (not client.mk)
# --enable-tests is used by configure (not client.mk)
export FOUND_MOZCONFIG := /c/Users/imelven/src/sandbox/mozconfig
